import {
  AdobeIcon,
  AliexpressIcon,
  AmazonIcon,
  AppleArcadeIcon,
  AppleIcon,
  AppleMusicIcon,
  AppStoreIcon,
  ArchIcon,
  AstroIcon,
  BandcampIcon,
  BitBucketIcon,
  BitcoinIcon,
  BlueskyIcon,
  BuyMeACoffeeIcon,
  CalendarIcon,
  CashAppIcon,
  ChatIcon,
  CourseraIcon,
  DebianIcon,
  DeviantArtIcon,
  DevtoIcon,
  DiscordIcon,
  GoogleDriveIcon,
  EbayIcon,
  EmacsIcon,
  EmailIcon,
  EtsyIcon,
  FacebookIcon,
  FedoraIcon,
  FigmaIcon,
  FreeBSDIcon,
  GentooIcon,
  GitHubIcon,
  GitLabIcon,
  GmailIcon,
  GnuIcon,
  GoogleIcon,
  GoogleMapsIcon,
  GooglePlayIcon,
  GumroadIcon,
  HackerNewsIcon,
  HeartIcon,
  ImdbIcon,
  InformationIcon,
  InstagramIcon,
  KofiIcon,
  LemonSqueezyIcon,
  LetterboxdIcon,
  LineIcon,
  LinkedInIcon,
  LinkIcon,
  LinuxMintIcon,
  MastodonIcon,
  MediumIcon,
  MessengerIcon,
  MetaIcon,
  NeovimIcon,
  NetflixIcon,
  NintendoIcon,
  NotionIcon,
  ObsidianIcon,
  OnlyFansIcon,
  OpenAIIcon,
  OutlookIcon,
  PaddleIcon,
  PatreonIcon,
  PhoneIcon,
  PinterestIcon,
  PlaystationIcon,
  QqIcon,
  ReadCVIcon,
  RedbubbleIcon,
  RedditIcon,
  RedHatIcon,
  RSSIcon,
  SignalIcon,
  SkypeIcon,
  SnapchatIcon,
  SoundcloudIcon,
  SpotifyIcon,
  SteamIcon,
  StripeIcon,
  SublimeTextIcon,
  SubstackIcon,
  TailwindIcon,
  TeamsIcon,
  TelegramIcon,
  TeslaIcon,
  ThreadsIcon,
  TikTokIcon,
  TumblrIcon,
  TwitchIcon,
  TwitterIcon,
  UbuntuIcon,
  UdemyIcon,
  VisualStudioCodeIcon,
  WeChatIcon,
  WeiboIcon,
  WhatsAppIcon,
  WikipediaIcon,
  XboxIcon,
  XIcon,
  YahooIcon,
  YouTubeIcon,
  ZedIcon,
  ZoomIcon,
} from "./Icons";

export const iconMap: { [key: string]: JSX.Element } = {
  adobe: <AdobeIcon />,
  aliexpress: <AliexpressIcon />,
  amazon: <AmazonIcon />,
  appStore: <AppStoreIcon />,
  apple: <AppleIcon />,
  appleArcade: <AppleArcadeIcon />,
  appleMusic: <AppleMusicIcon />,
  arch: <ArchIcon />,
  astro: <AstroIcon />,
  bandcamp: <BandcampIcon />,
  bitbucket: <BitBucketIcon />,
  bitcoin: <BitcoinIcon />,
  bluesky: <BlueskyIcon />,
  buyMeACoffee: <BuyMeACoffeeIcon />,
  calendar: <CalendarIcon />,
  cashApp: <CashAppIcon />,
  chat: <ChatIcon />,
  coursera: <CourseraIcon />,
  debian: <DebianIcon />,
  devto: <DevtoIcon />,
  deviantArt: <DeviantArtIcon />,
  discord: <DiscordIcon />,
  ebay: <EbayIcon />,
  emacs: <EmacsIcon />,
  email: <EmailIcon />,
  etsy: <EtsyIcon />,
  facebook: <FacebookIcon />,
  fedora: <FedoraIcon />,
  figma: <FigmaIcon />,
  freebsd: <FreeBSDIcon />,
  gentoo: <GentooIcon />,
  github: <GitHubIcon />,
  gitlab: <GitLabIcon />,
  gmail: <GmailIcon />,
  gnu: <GnuIcon />,
  google: <GoogleIcon />,
  googleDrive: <GoogleDriveIcon />,
  googleMaps: <GoogleMapsIcon />,
  googlePlay: <GooglePlayIcon />,
  gumroad: <GumroadIcon />,
  hackerNews: <HackerNewsIcon />,
  heart: <HeartIcon />,
  imdb: <ImdbIcon />,
  information: <InformationIcon />,
  instagram: <InstagramIcon />,
  kofi: <KofiIcon />,
  lemonSqueezy: <LemonSqueezyIcon />,
  letterboxd: <LetterboxdIcon />,
  line: <LineIcon />,
  link: <LinkIcon />,
  linkedIn: <LinkedInIcon />,
  // linux
  linuxMint: <LinuxMintIcon />,
  mastodon: <MastodonIcon />,
  medium: <MediumIcon />,
  messenger: <MessengerIcon />,
  meta: <MetaIcon />,
  neovim: <NeovimIcon />,
  netflix: <NetflixIcon />,
  nintendo: <NintendoIcon />,
  notion: <NotionIcon />,
  obsidian: <ObsidianIcon />,
  onlyfans: <OnlyFansIcon />,
  openai: <OpenAIIcon />,
  outlook: <OutlookIcon />,
  paddle: <PaddleIcon />,
  patreon: <PatreonIcon />,
  phone: <PhoneIcon />,
  pinterest: <PinterestIcon />,
  playstation: <PlaystationIcon />,
  qq: <QqIcon />,
  readcv: <ReadCVIcon />,
  redbubble: <RedbubbleIcon />,
  reddit: <RedditIcon />,
  redHat: <RedHatIcon />,
  rss: <RSSIcon />,
  signal: <SignalIcon />,
  skype: <SkypeIcon />,
  snapchat: <SnapchatIcon />,
  soundcloud: <SoundcloudIcon />,
  spotify: <SpotifyIcon />,
  steam: <SteamIcon />,
  stripe: <StripeIcon />,
  sublimeText: <SublimeTextIcon />,
  substack: <SubstackIcon />,
  tailwind: <TailwindIcon />,
  teams: <TeamsIcon />,
  telegram: <TelegramIcon />,
  tesla: <TeslaIcon />,
  threads: <ThreadsIcon />,
  tiktok: <TikTokIcon />,
  tumblr: <TumblrIcon />,
  twitch: <TwitchIcon />,
  twitter: <TwitterIcon />,
  ubuntu: <UbuntuIcon />,
  udemy: <UdemyIcon />,
  // venmo
  visualStudioCode: <VisualStudioCodeIcon />,
  wechat: <WeChatIcon />,
  weibo: <WeiboIcon />,
  whatsApp: <WhatsAppIcon />,
  wikipedia: <WikipediaIcon />,
  x: <XIcon />,
  xbox: <XboxIcon />,
  yahoo: <YahooIcon />,
  youtube: <YouTubeIcon />,
  zed: <ZedIcon />,
  zoom: <ZoomIcon />,
};
